name: CMake C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: build
      run: mkdir -p linux_build && cd linux_build && cmake .. && make -j 4

    - name: 1.sum_of_two_numbers
      run: pwd && cd bin && sudo ./1.sum_of_two_numbers 
    
    - name: 2.add_two_numbers
      run: pwd && cd bin && sudo ./2.add_two_numbers 34  54
    
    - name: 3.longest_substring_without_repeating_characters
      run: pwd && cd bin && sudo ./3.longest_substring_without_repeating_characters  dsfds
      
    - name: 4.find_the_median_of_two_positive_arrays
      run: pwd && cd bin && sudo ./4.find_the_median_of_two_positive_arrays
      
    - name: 5.longest_palindromic_substring
      run: pwd && cd bin && sudo ./5.longest_palindromic_substring
      
    - name: 6.zigzag_conversion
      run: pwd && cd bin && sudo ./6.zigzag_conversion
      
    - name: 7.reverse_integer
      run: pwd && cd bin && sudo ./7.reverse_integer
      
    - name: 8.string_to_integer
      run: pwd && cd bin && sudo ./8.string_to_integer
      
      
    - name: 9.palindrome_number
      run: pwd && cd bin && sudo ./9.palindrome_number
      
    - name: 10.regular_expression_matching
      run: pwd && cd bin && sudo ./10.regular_expression_matching

    - name: 0011.盛最多水的容器
      run: pwd && cd bin && sudo ./0011.container_with_most_water 1 8 6 2 5 4 8 3 7

    - name: 0012.整数转罗马数字
      run: pwd && cd bin && sudo ./0012.integer_to_roman 1994
    
    - name: 0013.罗马数字转整数
      run: pwd && cd bin && sudo ./0013.roman_to_integer MCMXCIV

    - name: 0014.最长公共前缀
      run: pwd && cd bin && sudo ./0014.longest_common_prefix flower flow flight



    - name: 0015.三数之和
      run: pwd && cd bin && sudo ./0015.three_sum 

    - name: 0016.最接近的三数之和
      run: pwd && cd bin && sudo ./0016.3sum_closest

    - name: 0017.电话号码的字母组合
      run: pwd && cd bin && sudo ./0017.letter_combinations_of_phone_number 3434

    - name: 0018.四数之和
      run: pwd && cd bin && sudo ./0018.fourSum

    - name: 0019.删除链表的倒数第N个节点
      run: pwd && cd bin && sudo ./0019.remove_nth_node_from_endof_list 1 2 4 5 6 3

    - name: 0020.有效的括号
      run: pwd && cd bin && sudo ./0020.valid_parentheses

    - name: 0021.合并两个有序链表
      run: pwd && cd bin && sudo ./0021.merge_two_sorted_lists 1 2 4 7 1 3 4 7 89

    - name: 0049. 字母异位词分组
      run: pwd && cd bin && sudo ./0049.GroupAnagrams
      
    - name: 0062.不同路径
      run: pwd && cd bin && sudo ./0062.UniquePaths

    - name: 0063.不同路径II
      run: pwd && cd bin && sudo ./0063.UniquePathsII

    - name: 0069. x 的平方根
      run: pwd && cd bin && sudo ./0069.Sqrtx

    - name: 0086. 分隔链表
      run: pwd && cd bin && sudo ./0086.PartitionList

    - name: 0134.加油站
      run: pwd && cd bin && sudo ./0134.Gas_Station

    - name: 0148.排序链表
      run: pwd && cd bin && sudo ./0148.Sort_List 4 19 14 5 -3 1 8 5 11 15  -3
      
      
    - name: 0164. 最大间距
      run: pwd && cd bin && sudo ./0164.Maximum_Gap


    - name: 0211.add_and_search_word
      run: pwd && cd bin && sudo ./211.add_and_search_word
      
    - name: 0222.完全二叉树的节点个数
      run: pwd && cd bin && sudo ./0222.Count_Complete_Tree_Nodes

    - name: 0239. 滑动窗口最大值
      run: pwd && cd bin && sudo ./0239.SlidingWindowMaximum

    - name: 0242.有效的字母异位词
      run: pwd && cd bin && sudo ./0242.Valid_Anagram

    - name: 0268.丢失的数字
      run: pwd && cd bin && sudo ./0268.Missing_Number


    - name: 0283.移动零
      run: pwd && cd bin && sudo ./0283.Move_Zeroes

    - name: 0300. 最长递增子序列
      run: pwd && cd bin && sudo ./0300.LongestIncreasingSubsequence


    - name: 0328.奇偶链表
      run: pwd && cd bin && sudo ./0328.Odd_Even_Linked_List 1 2 3 4 5
      


    - name: 381. O(1) 时间插入、删除和获取随机元素 - 允许重复
      run: pwd && cd bin && sudo ./0381.Insert_Delete_GetRandom_O_Duplicates_allowed

    - name: 387. 字符串中的第一个唯一字符
      run: pwd && cd bin && sudo ./0387.FirstUniqueCharacterinaString

    - name: 0393. UTF-8 编码验证
      run: pwd && cd bin && sudo ./0393.UTF-8Validation

    - name: 0402.移掉K位数字
      run: pwd && cd bin && sudo ./0402.Remove_K_Digits 

    - name: 0406.根据身高重建队列
      run: pwd && cd bin && sudo ./0406.Queue_Reconstruction_by_Height

    - name: 452.用最少数量的箭引爆气球
      run: pwd && cd bin && sudo ./0452.Minimum_Number_of_Arrows_to_Burst_Balloons
      
    - name: 454. 四数相加 II
      run: pwd && cd bin && sudo ./0454.fourSumCount
      
    - name: 493.翻转对
      run: pwd && cd bin && sudo ./0493.ReversePairs

    - name: 0547. 省份数量
      run: pwd && cd bin && sudo ./0547.NumberofProvinces

    - name: 605. 种花问题
      run: pwd && cd bin && sudo ./0605.CanPlaceFlowers

    - name: 0621.任务调度器
      run: pwd && cd bin && sudo ./0621.TaskScheduler     
      
      
      

    - name: 0648.单词替换
      run: pwd && cd bin && sudo ./0648.Replace_Words


    - name: 0684. 冗余连接
      run: pwd && cd bin && sudo ./0684.RedundantConnection

    - name: 0720.词典中最长的单词
      run: pwd && cd bin && sudo ./0720.Longest_Word_in_Dictionary


    - name: 0738. 单调递增的数字
      run: pwd && cd bin && sudo ./0738.MonotoneIncreasingDigits

    - name: 0740. 删除并获得点数
      run: pwd && cd bin && sudo ./0740.DeleteandEarn

    - name: 0830. 较大分组的位置
      run: pwd && cd bin && sudo ./0830.PositionsofLargeGroups


    - name: 0867.转置矩阵
      run: pwd && cd bin && sudo ./0867.transpose_matrix

    - name: 0922.按奇偶排序数组II
      run: pwd && cd bin && sudo ./0922.Sort_Array_By_Parity_II 4 2 5 7


    - name: 0977.有序数组的平方
      run: pwd && cd bin && sudo ./0977.SquaresofaSorted_Array

    - name: 0990. 等式方程的可满足性
      run: pwd && cd bin && sudo ./0990.SatisfiabilityofEqualityEquations

    - name: 1011. 在 D 天内送达包裹的能力
      run: pwd && cd bin && sudo ./1011.CapacityToShipPackagesWithinDDays


    - name: 1030.距离顺序排列矩阵单元格
      run: pwd && cd bin && sudo ./1030.Matrix_Cells_in_Distance_Order  2 3 1 2

    - name: 1074.元素和为目标值的子矩阵数量
      run: pwd && cd bin && sudo ./1074.number_of_submatrices_thatJ_sum_to_target
     
    - name: 1122.数组的相对排序
      run: pwd && cd bin && sudo ./1122.Relative_Sort_Array
      
    - name: 1319. 连通网络的操作次数
      run: pwd && cd bin && sudo ./1319.NumberofOperationstoMakeNetworkConnected

    - name: 1370.上升下降字符串
      run: pwd && cd bin && sudo ./1370.Increasing_Decreasing_String
    
    - name: 1476.子矩形查询
      run: pwd && cd bin && sudo ./1476.Subrectangle_Queries

    - name: 1535.找出数组游戏的赢家
      run: pwd && cd bin && sudo ./1535.Find_the_Winner_of_an_Array_Game

    - name: 1552.两球之间的磁力
      run: pwd && cd bin && sudo ./1552.Magnetic_Force_Between_Two_Balls
      
    - name: 1578. 避免重复字母的最小删除成本
      run: pwd && cd bin && sudo ./1578.MinimumDeletionCosttoAvoidRepeatingLetters
      
    - name: 1579. 保证图可完全遍历
      run: pwd && cd bin && sudo ./1579.RemoveMaxNumberofEdgestoKeepGraphFullyTraversable


    - name: 1584. 连接所有点的最小费用
      run: pwd && cd bin && sudo ./1584.MinCosttoConnectAllPoints



    - name: 1588.所有奇数长度子数组的和
      run: pwd && cd bin && sudo ./1588.Sum_of_All_Odd_Length_Subarrays
      
      
      
    - name: 1638.统计只差一个字符的子串数目
      run: pwd && cd bin && sudo ./1638.Count_Substrings_That_Differ_by_One_Character

    - name: 1734. 解码异或后的排列
      run: pwd && cd bin && sudo ./1734.DecodeXORedPermutation


    - name: 5243. 同积元组
      run: pwd && cd bin && sudo ./5243.TuplewithSameProduct

    - name: 5630. 删除子数组的最大得分
      run: pwd && cd bin && sudo ./5630.MaximumErasureValue

    - name: 5642. 大餐计数
      run: pwd && cd bin && sudo ./5642.CountGoodMeals 4567 83 34 34 34 343 232 232 232 232 232 23
      

    - name: 面试题 17.07. 婴儿名字
      run: pwd && cd bin && sudo ./Interview17.07.BabyNamesLCCI

    - name: 面试题17.10.主要元素
      run: pwd && cd bin && sudo ./Interviewquestions17.10.Find_Majority_Element_LCCI

    - name: 面试题17.21.直方图的水量
      run: pwd && cd bin && sudo ./Interviewquestions17.21.Volume_of_Histogram_LCCI











