name: CMake C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: build
      run: mkdir -p linux_build && cd linux_build && cmake .. && make -j 4

    - name: 1.sum_of_two_numbers
      run: pwd && cd bin && sudo ./1.sum_of_two_numbers 
    
    - name: 2.add_two_numbers
      run: pwd && cd bin && sudo ./2.add_two_numbers 34  54
    
    - name: 3.longest_substring_without_repeating_characters
      run: pwd && cd bin && sudo ./3.longest_substring_without_repeating_characters  dsfds
      
    - name: 4.find_the_median_of_two_positive_arrays
      run: pwd && cd bin && sudo ./4.find_the_median_of_two_positive_arrays
      
    - name: 5.longest_palindromic_substring
      run: pwd && cd bin && sudo ./5.longest_palindromic_substring
      
    - name: 6.zigzag_conversion
      run: pwd && cd bin && sudo ./6.zigzag_conversion
      
    - name: 7.reverse_integer
      run: pwd && cd bin && sudo ./7.reverse_integer
      
    - name: 8.string_to_integer
      run: pwd && cd bin && sudo ./8.string_to_integer
      
      
    - name: 9.palindrome_number
      run: pwd && cd bin && sudo ./9.palindrome_number
      
    - name: 10.regular_expression_matching
      run: pwd && cd bin && sudo ./10.regular_expression_matching

    - name: 11.盛最多水的容器
      run: pwd && cd bin && sudo ./11.盛最多水的容器 1 8 6 2 5 4 8 3 7

    - name: 12.整数转罗马数字
      run: pwd && cd bin && sudo ./12.整数转罗马数字 1994
    
    - name: 13.罗马数字转整数
      run: pwd && cd bin && sudo ./13.罗马数字转整数 MCMXCIV

    - name: 14.最长公共前缀
      run: pwd && cd bin && sudo ./14.最长公共前缀 flower flow flight



    - name: 15.三数之和
      run: pwd && cd bin && sudo ./15.三数之和 

    - name: 16.最接近的三数之和
      run: pwd && cd bin && sudo ./16.最接近的三数之和

    - name: 17.电话号码的字母组合
      run: pwd && cd bin && sudo ./17.电话号码的字母组合 3434

    - name: 18.四数之和
      run: pwd && cd bin && sudo ./18.四数之和

    - name: 19.删除链表的倒数第N个节点
      run: pwd && cd bin && sudo ./19.删除链表的倒数第N个节点 1 2 4 5 6 3

    - name: 20.有效的括号
      run: pwd && cd bin && sudo ./20.有效的括号 

    - name: 21.合并两个有序链表
      run: pwd && cd bin && sudo ./21.合并两个有序链表 1 2 4 7 1 3 4 7 89

    - name: 134.加油站
      run: pwd && cd bin && sudo ./134.加油站

    - name: 148.排序链表
      run: pwd && cd bin && sudo ./148.排序链表 4 19 14 5 -3 1 8 5 11 15  -3

    - name: 211.add_and_search_word
      run: pwd && cd bin && sudo ./211.add_and_search_word
      
    - name: 222.完全二叉树的节点个数
      run: pwd && cd bin && sudo ./0222.Count_Complete_Tree_Nodes

    - name: 242.有效的字母异位词
      run: pwd && cd bin && sudo ./242.有效的字母异位词

    - name: 283.移动零
      run: pwd && cd bin && sudo ./283.移动零

    - name: 328.奇偶链表
      run: pwd && cd bin && sudo ./328.奇偶链表 1 2 3 4 5
      


    - name: 381. O(1) 时间插入、删除和获取随机元素 - 允许重复
      run: pwd && cd bin && sudo ./0381.Insert_Delete_GetRandom_O_Duplicates_allowed

    - name: 402.移掉K位数字
      run: pwd && cd bin && sudo ./402.移掉K位数字 

    - name: 406.根据身高重建队列
      run: pwd && cd bin && sudo ./406.根据身高重建队列

    - name: 452.用最少数量的箭引爆气球
      run: pwd && cd bin && sudo ./452.用最少数量的箭引爆气球

    - name: 648.单词替换
      run: pwd && cd bin && sudo ./648.单词替换


    - name: 867.转置矩阵
      run: pwd && cd bin && sudo ./867.转置矩阵

    - name: 922.按奇偶排序数组II
      run: pwd && cd bin && sudo ./922.按奇偶排序数组II 4 2 5 7


    - name: 977.有序数组的平方
      run: pwd && cd bin && sudo ./977.有序数组的平方

    - name: 1030.距离顺序排列矩阵单元格
      run: pwd && cd bin && sudo ./1030.距离顺序排列矩阵单元格  2 3 1 2

    - name: 1074.元素和为目标值的子矩阵数量
      run: pwd && cd bin && sudo ./1074.元素和为目标值的子矩阵数量
     
    - name: 1122.数组的相对排序
      run: pwd && cd bin && sudo ./1122.数组的相对排序
    
    - name: 1476.子矩形查询
      run: pwd && cd bin && sudo ./1476.子矩形查询

    - name: 1535.找出数组游戏的赢家
      run: pwd && cd bin && sudo ./1535.找出数组游戏的赢家

    - name: 1552.两球之间的磁力
      run: pwd && cd bin && sudo ./1552.两球之间的磁力
      

    - name: 1588.所有奇数长度子数组的和
      run: pwd && cd bin && sudo ./1588.所有奇数长度子数组的和
      
      
      
    - name: 1638.统计只差一个字符的子串数目
      run: pwd && cd bin && sudo ./1638.统计只差一个字符的子串数目
      
      
    - name: 面试题17.10.主要元素
      run: pwd && cd bin && sudo ./面试题17.10.主要元素

    - name: 面试题17.21.直方图的水量
      run: pwd && cd bin && sudo ./面试题17.21.直方图的水量











