name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: build
      run: mkdir -p linux_build && cd linux_build && cmake .. && make -j 4

    - name: 1.sum_of_two_numbers
      run: pwd && cd bin && sudo ./1.sum_of_two_numbers 
    
    - name: 2.add_two_numbers
      run: pwd && cd bin && sudo ./2.add_two_numbers 34  54
    
    - name: 3.longest_substring_without_repeating_characters
      run: pwd && cd bin && sudo ./3.longest_substring_without_repeating_characters  dsfds
      
    - name: 4.find_the_median_of_two_positive_arrays
      run: pwd && cd bin && sudo ./4.find_the_median_of_two_positive_arrays
      
    - name: 5.longest_palindromic_substring
      run: pwd && cd bin && sudo ./5.longest_palindromic_substring
      
    - name: 6.zigzag_conversion
      run: pwd && cd bin && sudo ./6.zigzag_conversion
      
    - name: 7.reverse_integer
      run: pwd && cd bin && sudo ./7.reverse_integer
      
    - name: 8.string_to_integer
      run: pwd && cd bin && sudo ./8.string_to_integer
      
      
    - name: 9.palindrome_number
      run: pwd && cd bin && sudo ./9.palindrome_number
      
    - name: 10.regular_expression_matching
      run: pwd && cd bin && sudo ./10.regular_expression_matching

    - name: 11.盛最多水的容器
      run: pwd && cd bin && sudo ./11.盛最多水的容器 1 8 6 2 5 4 8 3 7

    - name: 12.整数转罗马数字
      run: pwd && cd bin && sudo ./12.整数转罗马数字 1994
    
    - name: 13.罗马数字转整数
      run: pwd && cd bin && sudo ./13.罗马数字转整数 MCMXCIV

    - name: 14.最长公共前缀
      run: pwd && cd bin && sudo ./14.最长公共前缀 flower flow flight



    - name: 15.三数之和
      run: pwd && cd bin && sudo ./15.三数之和 

    - name: 16.最接近的三数之和
      run: pwd && cd bin && sudo ./16.最接近的三数之和

    - name: 17.电话号码的字母组合
      run: pwd && cd bin && sudo ./17.电话号码的字母组合 3434

    - name: 18.四数之和
      run: pwd && cd bin && sudo ./18.四数之和

    - name: 211.add_and_search_word
      run: pwd && cd bin && sudo ./211.add_and_search_word
    
      
      
      
      
    
      
      
      
    
